Better shell options

diff --git a/email-relay/runit_opendkim b/email-relay/runit_opendkim
--- a/email-relay/runit_opendkim
+++ b/email-relay/runit_opendkim
@@ -1,4 +1,8 @@
 #!/bin/sh
+set -eu
+#set -o pipefail -o posix
+#shopt -s failglob
+#set -x
 
 if [ "$(stat -c %u /usr/local/etc/dkim)" != "$(id -u opendkim)" ] || [ "$(stat -c %g /usr/local/etc/dkim)" != "$(id -g postfix)" ]; then
 	chown -R opendkim:postfix /usr/local/etc/dkim
diff --git a/tomcat/runit_tomcat b/tomcat/runit_tomcat
--- a/tomcat/runit_tomcat
+++ b/tomcat/runit_tomcat
@@ -1,4 +1,8 @@
 #!/bin/sh
+set -eu
+#set -o pipefail -o posix
+#shopt -s failglob
+#set -x
 
 #if [ -x /usr/bin/authbind ]; then
 #	/usr/bin/authbind --deep "$CATALINA_HOME/bin/catalina.sh" start $*
